# Ref: https://github.com/SteveMacenski/slam_toolbox/blob/dashing-devel/config/mapper_params_online_sync.yaml
# Descriptions of the parameters are lister here: https://github.com/SteveMacenski/slam_toolbox#solver-params
slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Toolbox Params: https://github.com/SteveMacenski/slam_toolbox/tree/foxy-devel#toolbox-params
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    # Switch to 'localization' if needed
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    # if 0 never publishes odometry
    transform_publish_period: 0.02
    map_update_interval: 2.5
    # 2D占有マップの分解能。1m四方のフィールドで動かすため、分解能を上げる
    resolution: 0.01
    # LiDARの最大レンジ: URG: 5.6 m, LDS-01: 3.5 m, RPLiDAR: 12 m
    max_laser_range: 12.0 
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    # program needs a larger stack size to serialize large maps
    stack_size_to_use: 40000000  # bytes
    enable_interactive_mode: true

    # Matcher Params: https://github.com/SteveMacenski/slam_toolbox/tree/foxy-devel#matcher-params
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.15 
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.0
    loop_search_maximum_distance: 2.5
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true