<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>raspimouse_navigation</name>
    <version>3.1.0</version>
    <description>Robot-specific Nav2 configuration for Raspberry Pi Mouse</description>
    <maintainer email="shop@rt-net.jp">RT Corporation</maintainer>

    <license>Apache License 2.0</license>

    <url type="repository">https://github.com/rt-net/raspimouse_slam_navigation_ros2</url>
    <url type="bugtracker">https://github.com/rt-net/raspimouse_slam_navigation_ros2/issues</url>
    <author email="kozasa@rt-net.jp">Shuhei Kozasa</author>
    <author email="s.aoki@rt-net.jp">Shota Aoki</author>
    <author email="yusuke.kato@rt-net.jp">Yusuke Kato</author>
    <author email="kurasawa@rt-net.jp">Kazushi Kurasawa</author>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>ament_index_python</exec_depend>
    <exec_depend>dwb_core</exec_depend>
    <exec_depend>dwb_critics</exec_depend>
    <exec_depend>dwb_plugins</exec_depend>
    <exec_depend>hls_lfcd_lds_driver</exec_depend>
    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>
    <exec_depend>lifecycle_msgs</exec_depend>
    <exec_depend>nav2_amcl</exec_depend>
    <exec_depend>nav2_behaviors</exec_depend>
    <exec_depend>nav2_bt_navigator</exec_depend>
    <exec_depend>nav2_controller</exec_depend>
    <exec_depend>nav2_costmap_2d</exec_depend>
    <exec_depend>nav2_lifecycle_manager</exec_depend>
    <exec_depend>nav2_map_server</exec_depend>
    <exec_depend>nav2_navfn_planner</exec_depend>
    <exec_depend>nav2_planner</exec_depend>
    <exec_depend>nav2_rviz_plugins</exec_depend>
    <exec_depend>nav2_velocity_smoother</exec_depend>
    <exec_depend>nav2_waypoint_follower</exec_depend>
    <exec_depend>raspimouse</exec_depend>
    <exec_depend>raspimouse_slam</exec_depend>
    <exec_depend>rplidar_ros</exec_depend>
    <exec_depend>rviz2</exec_depend>
    <exec_depend>urg_node</exec_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
